interface ITestConfig {
  SLACKBOT_ID: string;
  SLACKBOT_TOKEN: string;
  SLACK_USER_ID: string;
  SLACK_USER_TOKEN: string;
  SLACK_PRIVATE_CHANNEL: string;
  SLACK_PUBLIC_CHANNEL: string;
  SLACK_PUBLIC_CHANNEL_FILE_ID: string;
  CLOUD_COMPUTER_SLACKBOT_SERVER_HOST: string;
  SLACK_TEAM_ID: string;
}

export const {
  SLACKBOT_ID,
  SLACKBOT_TOKEN,
  SLACK_USER_ID,
  SLACK_USER_TOKEN,
  SLACK_PRIVATE_CHANNEL,
  SLACK_PUBLIC_CHANNEL,
  SLACK_PUBLIC_CHANNEL_FILE_ID,
  SLACK_TEAM_ID,
  CLOUD_COMPUTER_SLACKBOT_SERVER_HOST = 'localhost',
}: ITestConfig = <any> process.env;
