version: '3.5'

networks:
  slack-backend:
    driver: bridge

services:

  api:
    image: node:11-alpine
    command: yarn start
    restart: on-failure
    labels:
      namespace: slack
      tier: api
    environment:
      STEMN_SLACK_SIGNING_SECRET: $STEMN_SLACK_SIGNING_SECRET
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      STEMN_SLACK_BOT_SERVER_PORT: 3000
      STEMN_API_TOKEN: $STEMN_API_TOKEN
      STEMN_API_HOST: $STEMN_API_HOST
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    networks:
      - slack-backend

  webhooks:
    image: webhookrelay/webhookrelayd:latest
    entrypoint: ./relayd --mode tunnel
    restart: on-failure
    labels:
      namespace: slack
      tier: webhook
    environment:
      KEY: $WEBHOOK_RELAY_KEY
      SECRET: $WEBHOOK_RELAY_SECRET
    networks:
      - slack-backend
