export interface IStemnConfig {
  CLOUD_COMPUTER_API_HOST: string;
  CLOUD_COMPUTER_API_PROTOCOL: string;
  CLOUD_COMPUTER_API_PORT: string;
  CLOUD_COMPUTER_API_TOKEN: string;
}

export const {
  CLOUD_COMPUTER_API_HOST,
  CLOUD_COMPUTER_API_PROTOCOL,
  CLOUD_COMPUTER_API_PORT,
  CLOUD_COMPUTER_API_TOKEN,
}: IStemnConfig = <any> process.env;
